/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.vprud

class App {
    val greeting: String
        get() {
            return "Hello World! from ${System.getProperty("java.vendor")} ${System.getProperty("java.version")}"
        }
}

fun main() {
    println(App().greeting)
}
