/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.vprud

import io.github.cdimascio.dotenv.dotenv
import okhttp3.OkHttpClient

fun main() {
    val env = dotenv()

    val tgToken = env["TG_TOKEN"] ?: error("TG_TOKEN not set in .env")
    val githubToken = dotenv()["GITHUB_TOKEN"] ?: error("GITHUB_TOKEN not set in .env")

    val httpClient = OkHttpClient()
    val gitHubClient = GitHubClient(httpClient, githubToken)
    val tracker = GitHubIssueTracker(gitHubClient)
    val checker = IssueUpdateChecker(tracker)
    val botService = createDefaultBotService(checker)

    botService.startBot(
        tgToken,
        tracker,
    )
}
